### ISSUE TITLE
support for trio besides asyncio

### ISSUE THREAD

**Issue by kantrol** [gijzelaerr/python-snap7#177]
**Enhancement:**
Just saw that recently asyncio support came in. It would be great if this could be extended to other async frameworks.

With [anyio](https://github.com/agronholm/anyio) there is a support library available to be independent of the async framework: 

"**AnyIO** is a asynchronous compatibility API that allows applications and libraries written against it to run unmodified on asyncio, curio and trio."

**Comment by swamper123** [comment]
My opinion and philosophy about external libraries is, to use them as less as possible.
Especially if a library tries to cover three more libraries (two of them even external), it is becoming more difficult to handle something.
Asyncio is a solid built-in solution (since 3.6+) which isn't as complex as it was 4 years ago and is well supported. Nevertheless, feel free and make a fork with an anyio support solution.

Any other opinions about that?

**Comment by gijzelaerr** [comment]
Yes, I agree that we should keep the scope of python-snap7 minimal.

**Comment by kantrol** [comment]
Ok, that's a  fair opinion.
