### ISSUE TITLE
Writing only bit

### ISSUE THREAD

**Issue by zet-jaro** [gijzelaerr/python-snap7#37]
Hi everybody,

I'm sort of a neewb in programming but I made nice script in python for connecting to plc and doing somethin... anyway, I made it working for INT and CHAR but BIT is a little problem... like I would like to change DB DBB 2.1 from 0 to 1 without reading the whole byte and then parsing it, adding, summing and sending back :( is there any other way?

Thanks for answer!
Tom

**Comment by ussefdesouky** [comment]
Hello All, currently I can get bool but I can't set a bool

**Comment by ussefdesouky** [comment]
![image](https://user-images.githubusercontent.com/38999100/158240927-f43a3c74-7d4b-40e7-8e96-aa6aa03164fc.jpeg)

**Comment by swamper123** [comment]
Keep in mind, that utils.py contains many helper functions to transform datatypes (e.g. bytearray to int and vise versa). They don't perform a read/write request with the sps.

From the function:

```python
def set_bool(bytearray_: bytearray, byte_index: int, bool_index: int, value: bool):
    """Set boolean value on location in bytearray.

    Args:
        bytearray_: buffer to write to.
        byte_index: byte index to write to.
        bool_index: bit index to write to.
        value: value to write.

    Examples:
        >>> buffer = bytearray([0b00000000])
        >>> set_bool(buffer, 0, 0, True)
        >>> buffer
            bytearray(b"\\x01")
    """
```

I guess `DB_NUMBER` is the number of the db, but not the array you would like to write to.
Second parameter is about the position of your byte in your bytearray (which could be larger).
Third parameter is about the position of the bit in your byte.
And the last one (either 1,0, True, False) is you value.

You may ask yourself, why you need the byte position in your bytearray, well this is because python isn't handling bits so well atm.
