### ISSUE TITLE
Snap7Exception is not used

### ISSUE THREAD

**Issue by kustkust** [gijzelaerr/python-snap7#519]
All methods raises a standart exceptions such as RuntimeError or ValueError, witch makes it difficult to handle errors from snap7 because they may mixup with other errors.

**Comment by gijzelaerr** [comment]
this is intentional, if you pass a wrong value to python-snap7 it will raise a value error. If you pass the wrong type to python-snap7 it will raise a type error. if something is wrong with the runtime (can't find DLL) snap7 will very quickly raise a runtime error. We didn't find the need anymore for our custom exception, since it was not adding a lot of value.
