### ISSUE TITLE
snap7 module not found windows 10

### ISSUE THREAD

**Issue by vrindakm** [gijzelaerr/python-snap7#78]
Hello

I am a new to python (and to GitHub) and am trying it out for an automation project of mine.
I am trying to use 64-bit Python 3.5.3 with 64 bit Snap7 on Windows 10 (also 64 bit).
I have copied the .dll and .lib files of snap7 and added it to system32 folder of windows.
I have also copied it to my python path.
But, when I import snap7 , it says 'Importerror: no module named snap7'
Does python-snap7 work in Windows 10? The document said it 'may' work on other OS.
Pardon me if this is trivial. It would be very helpful if I can get some guidance.

Thank you.

**Comment by gijzelaerr** [comment]
it should work. Maybe you need to modify the security of the dll? Maybe downloaded DLL's are not trusted by default on windows 10. Right click on the DLL in your system32 folder and somewhere there it should give an option to enable "trust this dll downloaded from a different computer".

Otherwise, make sure if system32 is in your PATH, not sure if that is the case on 64 windows? 

Sorry, can't think of much else here, hope this helps.

**Comment by spreeker** [comment]
Switch to Ubuntu :)

**Comment by vrindakm** [comment]
@gijzelaerr : I did copy the files as admin..so there seems to be no issue with security and yes, the system32 is indeed in my PATH 
Thanks for replying.

@spreeker : unfortunately, two main softwares of my project are not compatible with ubuntu :)
Thanks for replying though.

**Comment by gijzelaerr** [comment]
check this. 
![unblock_file_in_properties-1](https://cloud.githubusercontent.com/assets/326308/24652792/71a6222c-1933-11e7-8a6e-2cfd012329c3.png)
otherwise make sure you have the right architecture, not the 32 bit one. I can't really help you much further than this.

**Comment by vrindakm** [comment]
I did. But I do not have this option at all. All I got was the admin permission request while copying them earlier.
![image](https://cloud.githubusercontent.com/assets/26895245/24652901/decaec70-1933-11e7-93fa-6c32f4595d5b.png)

I shall go through all of it again.Thanks for the help so far :)
